In [1]:
import numpy as np

In [2]:
x = np.array([45,56,67,60])
print(x)
print(type(x))
print(x.dtype)

[45 56 67 60]
<class 'numpy.ndarray'>
int32


In [3]:
x = np.array([45,56,67,8.9])
print(x)
print(type(x))
print(x.dtype)

[45.  56.  67.   8.9]
<class 'numpy.ndarray'>
float64


In [4]:
x = np.array(["A",56,67,8.9])
print(x)
print(type(x))
print(x.dtype)

['A' '56' '67' '8.9']
<class 'numpy.ndarray'>
<U32


In [6]:
a = np.array([10,20,30,40])
b = a.reshape(2,2)
print(b)
print(b.shape)

[[10 20]
 [30 40]]
(2, 2)


In [7]:
c = np.arange(3,4)
print(c)
type(c)

[3]


numpy.ndarray

In [10]:
d = np.array([1.43, 3.45, 2.45])
print(d)
np.around(d,1)

[1.43 3.45 2.45]


array([1.4, 3.4, 2.4])

In [14]:
d = np.array([1.3467, 3.10987, 4.912])
print(d)
print(np.around(np.sqrt(d),2))

[1.3467  3.10987 4.912  ]
[1.16 1.76 2.22]


a1 = np.array([[3,4,5,6],[4,5,6,8],[7,5,9,np.NaN]])
print(a1)
a1.type

In [16]:
a1 = np.array([[3,4,5,6],[4,5,6,8],[7,5,9,np.NaN]]) 
print(a1) 
a1.dtype

[[ 3.  4.  5.  6.]
 [ 4.  5.  6.  8.]
 [ 7.  5.  9. nan]]


dtype('float64')

In [17]:
a1 = np.array([[3,4,5,6],[4,5,6,8],[7,5,9,np.NaN]]) 
a1_copy1 = a1.astype(str)
print(a1_copy1)
a1_copy1.dtype

[['3.0' '4.0' '5.0' '6.0']
 ['4.0' '5.0' '6.0' '8.0']
 ['7.0' '5.0' '9.0' 'nan']]


dtype('<U32')

In [18]:
a2 = np.array([[3,4,5,6],[4,5,6,8],[7,5,9,12]])
a2


array([[ 3,  4,  5,  6],
       [ 4,  5,  6,  8],
       [ 7,  5,  9, 12]])

In [19]:
print(a2.sum(axis=1))

[18 23 33]


In [20]:
print(a2.sum(axis=0))

[14 14 20 26]


In [24]:
a3 = np.array([[3,4,5],[5,6,8],[7,5,9]])
a3
np.fill_diagonal(a3,0)
a3

array([[0, 4, 5],
       [5, 0, 8],
       [7, 5, 0]])

In [26]:
a0 = np.array([[3,4,5],[5,6,8],[7,5,9]])
a0
np.fill_diagonal(a0,0)
a0

array([[0, 4, 5],
       [5, 0, 8],
       [7, 5, 0]])

In [28]:
A = np.array([[1,2], [2,3]])
B = np.array([[2,3], [3,6]])
C = np.matmul(A, B)
print(C)

[[ 8 15]
 [13 24]]


In [29]:
a4 = np.array([[3,4,5],[5,6,8],[7,5,9],[5,5,7]])
a4


array([[3, 4, 5],
       [5, 6, 8],
       [7, 5, 9],
       [5, 5, 7]])